[package]
name = "env"
version = "0.2.0"
edition = "2021"

[dependencies]
nix = "0.28.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
users = "0.11"
anyhow = "1.0"
shellexpand = "3.0"
