[package]
name = "env"
version = "0.2.0"
edition = "2021"

[dependencies]
nix = { version = "0.28.0", features = ["fs", "mount", "sched", "process", "user"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
shellexpand = "3.0"
